SoapService/force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor Event</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Sensor Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SoapService/force-app/main/default/objects/Sensor_Event__c/fields/Next_Event__c.field-meta.xml
<CustomField>
    <fullName>Next_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next Event</label>
    <referenceTo>Sensor_Event__c</referenceTo>
    <relationshipLabel>Next Events (Next Event)</relationshipLabel>
    <relationshipName>Next_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

SoapService/force-app/main/default/objects/Sensor_Event__c/fields/X__c.field-meta.xml
<CustomField>
    <fullName>X__c</fullName>
    <label>X</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

SoapService/force-app/main/default/objects/Sensor_Event__c/fields/Y__c.field-meta.xml
<CustomField>
    <fullName>Y__c</fullName>
    <label>Y</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

SoapService/force-app/main/default/objects/Sensor_Event__c/fields/Z__c.field-meta.xml
<CustomField>
    <fullName>Z__c</fullName>
    <label>Z</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

SoapService/force-app/main/default/classes/Tests/TestDataFactory.cls
public class TestDataFactory {
    public static Sensor__c generateSensor(String sensorName) {
        Account a = generateAccount('accName');

        Sensor__c sensor = new Sensor__c(Account_Id__c=a.id, Name=sensorName);
        insert sensor;

        return sensor;
    }

    public static Account generateAccount(String accName) {
        Account a = new Account(Name=accName);
        insert a;

        return a;
    }

    public static List<Sensor_Event__c> generateEventChain(Id sensorId, Integer chainLength) {
        List<Sensor_Event__c> events = new List<Sensor_Event__c>();

        for(Integer i = 0; i < chainLength; i++) {
            Sensor_Event__c event = new Sensor_Event__c(Sensor__c = sensorId, X__c = 1.0, Y__c = 1.0, Z__c = 1.0);
            events.add(event);
        }

        insert events;

        for(Integer i = 0; i < chainLength; i++) {
            events[i].Previous_Event__c = (i != 0)? events[i - 1].Id : null;
            events[i].Next_Event__c = (i != events.size() -1)? events[i + 1].Id: null;
        }

        update events;

        return events;
    }
}